language: cpp
compiler:
- gcc
- clang
env:
  global:
  # encrypted Coverity-Scan token - do not change
  - secure: "O66/sTXcYBQQhdqgVj6ZMjssf8Hwd/36gYzrytmAdTUJ+A3MlP70XsZ+n47gGb+Am8Co676z1pj7QIFImU2ea23ZnzlQF92OpYIlWnq+heRPBtrk8wUQ052d6HX7Ik+/a1/OQGxsS4631igyw7zh5H++XAZMWfdO3vQq53dhwS0="
  - PROJECT_NAME=OpenMS/OpenMS
addons:
  coverity_scan:
    project:
      name: OpenMS/OpenMS
      description: The OpenMS project
    notification_email: sachsenberg@gmail.com
    build_command_prepend: ./tools/lnx-cibuild_coverity.configure.sh
    build_command: cmake --build _coverity_build
    branch_pattern: coverity_scan
before_script: ./tools/lnx-cibuild.before.sh
script: ./tools/lnx-cibuild.sh
# we need some more infos if something fails
after_failure:
  - env | sort
  - cat _build/CMakeCache.txt