language: cpp
compiler:
  - gcc
  - clang

# following lins configure coverity static code analysis for the coverity_scan branch 
env:
  global:
   #  The next declration is the encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
   - secure: "bWJedr1KAbqIYak/ecixNv5SwQFeUHHeFX/MbFsZ26cOYdFC+Nyb2iKJAu6DLvnTyAAo4jJOndd+Js4aQaSCuQv9twKiIaqzjz6CoFrPyJqS0ReFUZgA5eC058TW5PQdJcvxzgOyzeTot1xXGuvxlQw2jlE9MqJtahZdI3juN84="

addons:
  coverity_scan:
    project:
      name: "OpenMS/OpenMS"
      description: "The OpenMS project"
    notification_email: sachsenberg@gmail.com
    build_command_prepend: "./tools/lnx-cibuild.before.sh"
    build_command: "./tools/lnx-cibuild.sh"
    branch_pattern: coverity_scan

before_script:
  ./tools/lnx-cibuild.before.sh
script:
  ./tools/lnx-cibuild.sh
